draw_config:
  glyph_tap_size: 18
  glyphs:  # adapted from icons at https://tabler-icons.io/
    BSPC: |
      <svg viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none">
       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
       <path d="M20 6a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-11l-5 -5a1.5 1.5 0 0 1 0 -2l5 -5z"></path>
       <path d="M12 10l4 4m0 -4l-4 4"></path>
      </svg>
    SPACE: |
      <svg viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
        <path d="M4 10v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1 -1v-3"></path>
      </svg>
    ENTER:
      <svg viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
         <path d="M9 11l-4 4l4 4m-4 -4h11a4 4 0 0 0 0 -8h-1"></path>
      </svg>
    del: |
      <svg viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" transform="rotate(180, 9, 9)">
       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
       <path d="M20 6a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-11l-5 -5a1.5 1.5 0 0 1 0 -2l5 -5z"></path>
       <path d="M12 10l4 4m0 -4l-4 4"></path>
      </svg>
parse_config:
  preprocess: true
  raw_binding_map: {"lower_layer": "LOWER", "&RAISE": "RAISE", "adjust_layer": "ADJ", "&bootloader": "BOOT", "&sys_reset": "RESET"}
  skip_binding_parsing: false
  sticky_label: sticky
  trans_legend:
    t: "\u25BD"
    type: trans
  zmk_combos: {}
  zmk_keycode_map:
    AMPERSAND: '&'
    AMPS: '&'
    APOS: .
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
    RA(U): ü
    RA(O): ö
    RA(A): ä
    RA(S): ß
    RA(N5): €
    LOWER: 'LOWER'
